# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d496989438db9e5aeb65f554a3437d3858577b5a4af8c7deeb8dd7f8b56deb5461d493b9c8be4a39dd22dd47f13485296c2257475a11a6a6c0add5de2b2b3a77

test:
  secret_key_base: 800c55da338b6f1a2d53c8311bc3702ba3cf3d3a591e2c02265c1af82395d9f9375b8c3437bdfed0b2de9b277c2ac8216a1f1f48ac43f75ecc96f4565be9d8cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
